---
- name: Installa Java 17
  dnf:
    name: "{{ java_package }}"
    state: present

- name: Crea gruppo kafka
  group:
    name: "{{ kafka_user }}"
    state: present

- name: Crea utente kafka
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_user }}"
    shell: /bin/bash

- name: Scarica e estrai Kafka (che include ZK)
  unarchive:
    src: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/{{ kafka_dist }}.tgz"
    dest: /opt/
    remote_src: yes
    owner: "{{ kafka_user }}"
    group: "{{ kafka_user }}"

- name: Crea symlink per facilità d'uso
  file:
    src: "/opt/{{ kafka_dist }}"
    dest: "{{ install_dir }}"
    state: link
    owner: "{{ kafka_user }}"

- name: Configura /etc/hosts per la risoluzione dei nodi
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  with_items:
    - { ip: '192.168.52.128', name: 'kafka-1' }
    - { ip: '192.168.52.129', name: 'kafka-2' }
    - { ip: '192.168.52.130', name: 'kafka-3' }

- name: Installa supporto Python per gestione Firewall
  dnf:
    name: python3-firewall
    state: present

- name: Apri porte Kafka e ZooKeeper nel Firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 2181/tcp
    - 2888/tcp
    - 3888/tcp
    - 9092/tcp

- name: Configura logrotate per i log di Kafka
  copy:
    src: kafka-logrotate
    dest: /etc/logrotate.d/kafka
    owner: root
    group: root
    mode: '0644'